outputpath: experiments

data:
    train:
        label: data/train/label.json
        audio_feature: data/train/lms.csv
    val:
        label: data/val/label.json
        audio_feature: data/val/lms.csv
    vocab_file: data/train/vocab.pkl

dataloader_args:
    batch_size: 128
    num_workers: 4

audio_encoder: 
    type: CrnnEncoder
    args:
        input_dim: 64
        embed_dim: 256

text_encoder: 
    type: EmbeddingMeanEncoder
    args:
        embed_dim: 256

similarity_fn: 
    type: ExponentialNegativeL2
    args: {}

model: 
    type: NaiveModel
    args: {}

loss: 
    type: BinaryCrossEntropyLoss
    args: {}

optimizer: 
    type: Adam
    args:
        lr: 0.001
        weight_decay: 0.0

improvecriterion: loss

lr_scheduler:
    type: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.1
        patience: 5
        threshold: 0.001

early_stop: 10
epochs: 100
