data:
    test:
        dataset:
            type: datasets.single_phrase_dataset.AudioPhraseEvalDataset
            args:
                waveform: data/test/waveform.csv
                label: data/test/label.json
                # label: data/test/label_non_trivial_50percent.json
        collate_fn:
            type: datasets.collate_function.TextCollate
            args:
                pad_keys: [waveform]
                text_key: phrase
            tokenizer:
                type: datasets.text_tokenizer.DictTokenizer
                args:
                    vocabulary: data/audiocaps/vocab_state_dict.pkl
        duration: data/test/duration.csv

time_resolution: 0.04
window_size: 1
n_thresholds: 50
resume: best.pth
max_efprs: [400, 600, 800, 1000, Null]
output_psds: result_psds.txt
output_th_auc: result_th_auc.txt
output: result.txt
# output: non_trivial_50percent_samples/result.txt
